# Generated by Django 5.0.6 on 2024-06-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoriosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'laboratorio',
                'verbose_name_plural': 'laboratorios',
                'db_table': 'laboratorios',
            },
        ),
        migrations.CreateModel(
            name='MarcasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='ActivosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activo', models.CharField(max_length=12)),
                ('nombre_activo', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('EN_USO', 'En uso'), ('EN_REPARACION', 'En reparacion')], default='EN_USO', max_length=16)),
                ('descripcion', models.TextField(blank=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratoriosmodel')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marcasmodel')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'db_table': 'activos',
            },
        ),
    ]
