# Generated by Django 5.0.6 on 2024-06-04 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activosmodel',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='api.laboratoriosmodel'),
        ),
        migrations.AlterField(
            model_name='activosmodel',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='api.marcasmodel'),
        ),
    ]
