# Generated by Django 5.0.6 on 2024-06-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activosmodel_laboratorio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcasmodel',
            old_name='nombre',
            new_name='nombre_marca',
        ),
    ]
