# Generated by Django 5.0.6 on 2024-06-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_nombre_marcasmodel_nombre_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activosmodel',
            options={'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.AlterModelOptions(
            name='laboratoriosmodel',
            options={'verbose_name': 'Laboratorio', 'verbose_name_plural': 'Laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='marcasmodel',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
