# Generated by Django 5.0.6 on 2024-06-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activosmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcasmodel',
            old_name='nombre_marca',
            new_name='nombre',
        ),
    ]
